import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import { ClientWrapper } from "@/components/wrapper/ClientWrapper";
import "./globals.css";

const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${roboto.variable} antialiased`}>
        <AntdRegistry>
          <ClientWrapper>{children}</ClientWrapper>
        </AntdRegistry>
      </body>
    </html>
  );
}
